set(LIB_A_PACKAGE_NAME LibA)
set(LIB_A_LIB_NAME LibA)
set(LIB_A_LIB_VERSION 1.0.0)

set(LIB_A_IMPORT_LOC "${INSTALL_ROOT_DIR}/${PROJECT_MODULE_NAME}/${LIB_A_PACKAGE_NAME}/v${LIB_A_LIB_VERSION}/${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_VERSION}/cmake")

list(APPEND CMAKE_PREFIX_PATH ${LIB_A_IMPORT_LOC})

find_package(${LIB_A_PACKAGE_NAME} ${LIB_A_LIB_VERSION} REQUIRED CONFIG)